//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string XAML_MainWindowButtonBrowseContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonBrowseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse project folder.
        /// </summary>
        public static string XAML_MainWindowButtonBrowseToolTip {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonBrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix checked.
        /// </summary>
        public static string XAML_MainWindowButtonFixContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonFixContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes some problems.
        /// </summary>
        public static string XAML_MainWindowButtonFixToolTip {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonFixToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string XAML_MainWindowButtonRunContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonRunContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string XAML_MainWindowButtonRunToolTip {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonRunToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test generating.
        /// </summary>
        public static string XAML_MainWindowButtonTestGeneratingContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonTestGeneratingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test generating function that used by Fix method. (Not async).
        /// </summary>
        public static string XAML_MainWindowButtonTestGeneratingToolTip {
            get {
                return ResourceManager.GetString("XAML_MainWindowButtonTestGeneratingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoScroll.
        /// </summary>
        public static string XAML_MainWindowCheckBoxAutoscrollContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowCheckBoxAutoscrollContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string XAML_MainWindowCheckBoxCheckAllContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowCheckBoxCheckAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Quarantine.
        /// </summary>
        public static string XAML_MainWindowCheckBoxQuarantineContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowCheckBoxQuarantineContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on checked.
        /// </summary>
        public static string XAML_MainWindowCheckBoxRunCheckedContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowCheckBoxRunCheckedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string XAML_MainWindowStatusLabelContent {
            get {
                return ResourceManager.GetString("XAML_MainWindowStatusLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string XAML_MainWindowTabItemProblemsHeader {
            get {
                return ResourceManager.GetString("XAML_MainWindowTabItemProblemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Cleaner 1.0.
        /// </summary>
        public static string XAML_MainWindowTitleCodeCleaner {
            get {
                return ResourceManager.GetString("XAML_MainWindowTitleCodeCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test message from .
        /// </summary>
        public static string XAML_ProblemViewControlTextBlockMessageText {
            get {
                return ResourceManager.GetString("XAML_ProblemViewControlTextBlockMessageText", resourceCulture);
            }
        }
    }
}
